# coding: utf-8

"""
    ICFP Contest 2020 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.aliens_api_api import AliensApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAliensApiApi(unittest.TestCase):
    """AliensApiApi unit test stubs"""

    def setUp(self):
        self.api = api.aliens_api_api.AliensApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aliens_response_id_get(self):
        """Test case for aliens_response_id_get

        """
        pass

    def test_aliens_send_post(self):
        """Test case for aliens_send_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
