# coding: utf-8

"""
    ICFP Contest 2020 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.submissions_api_api import SubmissionsApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmissionsApiApi(unittest.TestCase):
    """SubmissionsApiApi unit test stubs"""

    def setUp(self):
        self.api = api.submissions_api_api.SubmissionsApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_submissions_get(self):
        """Test case for submissions_get

        """
        pass

    def test_submissions_submission_id_get(self):
        """Test case for submissions_submission_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
