# coding: utf-8

"""
    ICFP Contest 2020 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.submission_status import SubmissionStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmissionStatus(unittest.TestCase):
    """SubmissionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionStatus(self):
        """Test SubmissionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.submission_status.SubmissionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
