# coding: utf-8

"""
    ICFP Contest 2020 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.logs_api_api import LogsApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLogsApiApi(unittest.TestCase):
    """LogsApiApi unit test stubs"""

    def setUp(self):
        self.api = api.logs_api_api.LogsApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_logs_get(self):
        """Test case for logs_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
