# coding: utf-8

"""
    ICFP Contest 2020 API

    See <a href='https://github.com/icfpcontest2020/aliens-proxy-protocol' target='_blank'>https://github.com/icfpcontest2020/aliens-proxy-protocol<a/>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.games_api_api import GamesApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGamesApiApi(unittest.TestCase):
    """GamesApiApi unit test stubs"""

    def setUp(self):
        self.api = api.games_api_api.GamesApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_games_game_id_get(self):
        """Test case for games_game_id_get

        """
        pass

    def test_games_get(self):
        """Test case for games_get

        """
        pass

    def test_games_non_rating_get(self):
        """Test case for games_non_rating_get

        """
        pass

    def test_games_non_rating_run_post(self):
        """Test case for games_non_rating_run_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
