# coding: utf-8

"""
    ICFP Contest 2020 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.build_system_registration_info_dto import BuildSystemRegistrationInfoDto  # noqa: E501
from swagger_client.rest import ApiException


class TestBuildSystemRegistrationInfoDto(unittest.TestCase):
    """BuildSystemRegistrationInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildSystemRegistrationInfoDto(self):
        """Test BuildSystemRegistrationInfoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.build_system_registration_info_dto.BuildSystemRegistrationInfoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
