# coding: utf-8

"""
    ICFP Contest 2020 API

    See <a href='https://github.com/icfpcontest2020/aliens-proxy-protocol' target='_blank'>https://github.com/icfpcontest2020/aliens-proxy-protocol<a/>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.submission_for_tournament_scoreboard_dto import SubmissionForTournamentScoreboardDto  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmissionForTournamentScoreboardDto(unittest.TestCase):
    """SubmissionForTournamentScoreboardDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionForTournamentScoreboardDto(self):
        """Test SubmissionForTournamentScoreboardDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.submission_for_tournament_scoreboard_dto.SubmissionForTournamentScoreboardDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
