# coding: utf-8

"""
    ICFP Contest 2020 API

    See <a href='https://github.com/icfpcontest2020/aliens-proxy-protocol' target='_blank'>https://github.com/icfpcontest2020/aliens-proxy-protocol<a/>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ICFP Contest 2020 API",
    author_email="",
    url="",
    keywords=["Swagger", "ICFP Contest 2020 API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    See &lt;a href&#x3D;&#x27;https://github.com/icfpcontest2020/aliens-proxy-protocol&#x27; target&#x3D;&#x27;_blank&#x27;&gt;https://github.com/icfpcontest2020/aliens-proxy-protocol&lt;a/&gt;  # noqa: E501
    """
)
