# coding: utf-8

# flake8: noqa
"""
    ICFP Contest 2020 API

    See <a href='https://github.com/icfpcontest2020/aliens-proxy-protocol' target='_blank'>https://github.com/icfpcontest2020/aliens-proxy-protocol<a/>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.build_system_registration_info_dto import BuildSystemRegistrationInfoDto
from swagger_client.models.build_system_registration_status import BuildSystemRegistrationStatus
from swagger_client.models.game_dto import GameDto
from swagger_client.models.game_winner import GameWinner
from swagger_client.models.games_list_dto import GamesListDto
from swagger_client.models.lightning_scoreboard_dto import LightningScoreboardDto
from swagger_client.models.player_dto import PlayerDto
from swagger_client.models.problem_description_dto import ProblemDescriptionDto
from swagger_client.models.problem_dto import ProblemDto
from swagger_client.models.rating_dto import RatingDto
from swagger_client.models.registered_team_dto import RegisteredTeamDto
from swagger_client.models.submission_dto import SubmissionDto
from swagger_client.models.submission_for_tournament_scoreboard_dto import SubmissionForTournamentScoreboardDto
from swagger_client.models.submission_status import SubmissionStatus
from swagger_client.models.team_dto import TeamDto
from swagger_client.models.team_for_problems_scoreboard_dto import TeamForProblemsScoreboardDto
from swagger_client.models.team_for_total_scoreboard_dto import TeamForTotalScoreboardDto
from swagger_client.models.team_for_tournament_scoreboard_dto import TeamForTournamentScoreboardDto
from swagger_client.models.team_submission_dto import TeamSubmissionDto
from swagger_client.models.team_tournament_dto import TeamTournamentDto
from swagger_client.models.total_scoreboard_dto import TotalScoreboardDto
from swagger_client.models.tournament_dto import TournamentDto
from swagger_client.models.tournament_dto_type import TournamentDtoType
from swagger_client.models.tournament_scoreboard_dto import TournamentScoreboardDto
